"""Add other_specify and attachment_types fields

Revision ID: 086fdd5a61a2
Revises: aefcdb910500
Create Date: 2025-10-29 21:41:04.980344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086fdd5a61a2'
down_revision: Union[str, Sequence[str], None] = 'aefcdb910500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_logs', sa.Column('activities_other_specify', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('thematic_areas_other_specify', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('attachment_types', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorship_logs', 'attachment_types')
    op.drop_column('mentorship_logs', 'thematic_areas_other_specify')
    op.drop_column('mentorship_logs', 'activities_other_specify')
    # ### end Alembic commands ###
