"""Add LGA field to facilities table

Revision ID: 453d4e03b9a5
Revises: 086fdd5a61a2
Create Date: 2025-10-29 22:09:28.534168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453d4e03b9a5'
down_revision: Union[str, Sequence[str], None] = '086fdd5a61a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('lga', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_facilities_lga'), 'facilities', ['lga'], unique=False)
    op.create_index(op.f('ix_facilities_state'), 'facilities', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facilities_state'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_lga'), table_name='facilities')
    op.drop_column('facilities', 'lga')
    # ### end Alembic commands ###
