"""add_unified_notification_system)

Revision ID: 8b53bc9d0cff
Revises: 64353edf8841
Create Date: 2025-11-19 10:59:01.445640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b53bc9d0cff'
down_revision: Union[str, Sequence[str], None] = '64353edf8841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('specialist_log', 'comment', 'approval', 'rejection', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_log_id', sa.UUID(), nullable=True),
    sa.Column('related_comment_id', sa.UUID(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_comment_id'], ['log_comments.id'], ),
    sa.ForeignKeyConstraint(['related_log_id'], ['mentorship_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_related_comment_id'), 'notifications', ['related_comment_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_log_id'), 'notifications', ['related_log_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_sessions_chat_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_constraint(op.f('log_comments_mentorship_log_id_fkey'), 'log_comments', type_='foreignkey')
    op.create_foreign_key(None, 'log_comments', 'mentorship_logs', ['mentorship_log_id'], ['id'])
    op.create_index(op.f('ix_specialist_notifications_mentorship_log_id'), 'specialist_notifications', ['mentorship_log_id'], unique=False)
    op.drop_constraint(op.f('specialist_notifications_mentorship_log_id_fkey'), 'specialist_notifications', type_='foreignkey')
    op.drop_constraint(op.f('specialist_notifications_specialist_id_fkey'), 'specialist_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'specialist_notifications', 'users', ['specialist_id'], ['id'])
    op.create_foreign_key(None, 'specialist_notifications', 'mentorship_logs', ['mentorship_log_id'], ['id'])
    op.drop_constraint(op.f('user_specializations_user_id_fkey'), 'user_specializations', type_='foreignkey')
    op.create_foreign_key(None, 'user_specializations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_specializations', type_='foreignkey')
    op.create_foreign_key(op.f('user_specializations_user_id_fkey'), 'user_specializations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'specialist_notifications', type_='foreignkey')
    op.drop_constraint(None, 'specialist_notifications', type_='foreignkey')
    op.create_foreign_key(op.f('specialist_notifications_specialist_id_fkey'), 'specialist_notifications', 'users', ['specialist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('specialist_notifications_mentorship_log_id_fkey'), 'specialist_notifications', 'mentorship_logs', ['mentorship_log_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_specialist_notifications_mentorship_log_id'), table_name='specialist_notifications')
    op.drop_constraint(None, 'log_comments', type_='foreignkey')
    op.create_foreign_key(op.f('log_comments_mentorship_log_id_fkey'), 'log_comments', 'mentorship_logs', ['mentorship_log_id'], ['id'], ondelete='CASCADE')
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_question_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('followup_question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agent_request', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey')),
    sa.UniqueConstraint('chat_id', name=op.f('user_sessions_chat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sessions_chat_id'), 'user_sessions', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_log_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_comment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
