"""Add rejection fields to mentorship_logs

Revision ID: 9fdd958cc7ea
Revises: 453d4e03b9a5
Create Date: 2025-10-31 16:52:28.170970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdd958cc7ea'
down_revision: Union[str, Sequence[str], None] = '453d4e03b9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_logs', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mentorship_logs', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentorship_logs', 'rejection_reason')
    op.drop_column('mentorship_logs', 'rejected_at')
    # ### end Alembic commands ###
