"""Update models to match ACE2 PDF form

Revision ID: aefcdb910500
Revises: fd1bc4e8584a
Create Date: 2025-10-29 20:59:39.637613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aefcdb910500'
down_revision: Union[str, Sequence[str], None] = 'fd1bc4e8584a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentorship_log_id', sa.UUID(), nullable=False),
    sa.Column('skill_knowledge_transferred', sa.Text(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_cadre', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('competency_level', sa.String(length=100), nullable=True),
    sa.Column('followup_needed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_log_id'], ['mentorship_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_transfers_mentorship_log_id'), 'skills_transfers', ['mentorship_log_id'], unique=False)
    op.drop_index(op.f('ix_visit_objectives_mentorship_log_id'), table_name='visit_objectives')
    op.drop_table('visit_objectives')
    op.add_column('follow_ups', sa.Column('responsible_person', sa.String(length=255), nullable=True))
    op.add_column('follow_ups', sa.Column('target_date', sa.Date(), nullable=True))
    op.add_column('follow_ups', sa.Column('resources_needed', sa.Text(), nullable=True))
    op.add_column('follow_ups', sa.Column('priority', sa.String(length=50), nullable=True))
    op.drop_column('follow_ups', 'due_date')
    op.add_column('mentorship_logs', sa.Column('interaction_type', sa.String(length=50), nullable=True))
    op.add_column('mentorship_logs', sa.Column('duration_hours', sa.Integer(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('mentees_present', sa.JSON(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('activities_conducted', sa.JSON(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('thematic_areas', sa.JSON(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('strengths_observed', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('gaps_identified', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('root_causes', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('challenges_encountered', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('solutions_proposed', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('support_needed', sa.Text(), nullable=True))
    op.add_column('mentorship_logs', sa.Column('success_stories', sa.Text(), nullable=True))
    op.drop_column('mentorship_logs', 'progress_made')
    op.drop_column('mentorship_logs', 'identified_gaps')
    op.drop_column('mentorship_logs', 'facility_requests')
    op.drop_column('mentorship_logs', 'resources_needed')
    op.drop_column('mentorship_logs', 'trends_summary')
    op.drop_column('mentorship_logs', 'performance_summary')
    op.drop_column('mentorship_logs', 'lessons_learned')
    op.drop_column('mentorship_logs', 'previous_followup')
    op.drop_column('mentorship_logs', 'persistent_challenges')
    op.drop_column('mentorship_logs', 'visit_outcomes')
    op.drop_column('mentorship_logs', 'logistics_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentorship_logs', sa.Column('logistics_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('visit_outcomes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('persistent_challenges', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('previous_followup', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('lessons_learned', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('performance_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('trends_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('resources_needed', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('facility_requests', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('identified_gaps', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mentorship_logs', sa.Column('progress_made', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('mentorship_logs', 'success_stories')
    op.drop_column('mentorship_logs', 'support_needed')
    op.drop_column('mentorship_logs', 'solutions_proposed')
    op.drop_column('mentorship_logs', 'challenges_encountered')
    op.drop_column('mentorship_logs', 'root_causes')
    op.drop_column('mentorship_logs', 'gaps_identified')
    op.drop_column('mentorship_logs', 'strengths_observed')
    op.drop_column('mentorship_logs', 'thematic_areas')
    op.drop_column('mentorship_logs', 'activities_conducted')
    op.drop_column('mentorship_logs', 'mentees_present')
    op.drop_column('mentorship_logs', 'duration_minutes')
    op.drop_column('mentorship_logs', 'duration_hours')
    op.drop_column('mentorship_logs', 'interaction_type')
    op.add_column('follow_ups', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('follow_ups', 'priority')
    op.drop_column('follow_ups', 'resources_needed')
    op.drop_column('follow_ups', 'target_date')
    op.drop_column('follow_ups', 'responsible_person')
    op.create_table('visit_objectives',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mentorship_log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('objective_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentorship_log_id'], ['mentorship_logs.id'], name=op.f('visit_objectives_mentorship_log_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('visit_objectives_pkey'))
    )
    op.create_index(op.f('ix_visit_objectives_mentorship_log_id'), 'visit_objectives', ['mentorship_log_id'], unique=False)
    op.drop_index(op.f('ix_skills_transfers_mentorship_log_id'), table_name='skills_transfers')
    op.drop_table('skills_transfers')
    # ### end Alembic commands ###
