"""Increase attachment file_name column length to 255

Revision ID: d7e753b3f250
Revises: 9fdd958cc7ea
Create Date: 2025-11-01 07:19:50.844890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e753b3f250'
down_revision: Union[str, Sequence[str], None] = '9fdd958cc7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_name',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_name',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###
